name: CraftStories

# オプション設定
options:
  # バンドルプレフィックス
  bundleIdPrefix: CraftStories
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja

# Swift Package Managerのパッケージ設定
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.2.0
  ColorfulX:
    url: https://github.com/Lakr233/ColorfulX
    from: 5.3.1
  googlesignin-ios:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 4.4.3

# ターゲットごとの設定
targets:
  CraftStories:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "17.0.0"

    # 採用するFirebaseのサービス
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
#      - package: Firebase
#        product: FirebaseFirestoreSwift
      - package: ColorfulX
        product: ColorfulX
      - package: googlesignin-ios
        product: GoogleSignInSwift
      - package: Lottie
        product: Lottie

    # ソースコードとその他のファイル
    sources:
      - CraftStories
      - project.yml
    resources:
      - Resources

    # ビルド設定
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: algoria.CraftStories
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: algoria
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    # Info.plist設定
    info:
      path: CraftStories/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Light

  CraftStoriesTests:
    type: bundle.unit-test
    platform: iOS
    sources: [CraftStoriesTests]
    dependencies:
      - target: CraftStories


